apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Application
    name: sw-simple
  path: argo-app-patch.yaml
- path: image-patch.yaml
- path: deployment-patch.yaml
