apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: argo-app-patch.yaml
  target:
    kind: Application
    name: sw-simple
- path: image-patch.yaml
- path: deployment-patch.yaml
images:
- name: evilpandas/sw-simple
  newName: evilpandas/sw-simple
  newTag: dfcb910
