apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: deployment-patch.yaml
images:
- name: evilpandas/sw-simple
  newName: evilpandas/sw-simple
  newTag: 3b03c35
- name: sw-simple
  newName: evilpandas/sw-simple
  newTag: "7239894"
