name: Argo CD Deployment

on:
  push:
    branches:
      - main # Trigger build on push to main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          SHORT_TAG=$(git rev-parse --short HEAD)
          echo "SHORT_TAG=$SHORT_TAG" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Multi-Platform Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            evilpandas/sw-simple:${{ env.SHORT_TAG }}
            evilpandas/sw-simple:latest 

  deploy-to-stage:
    needs: build
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update Image Tag in Kustomization
        run: |
          cd .k8s/overlays/stage
          kustomize edit set image sw-simple=evilpandas/sw-simple:${{ env.SHORT_TAG }}

      - name: Deploy to Stage (Manual Approval)
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'argocd-deploy.yaml',
              ref: 'main',
              inputs: {
                environment: 'stage',
                image_tag: '${{ env.SHORT_TAG }}'
              }
            })

  deploy-to-prod:
    needs: deploy-to-stage
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'stage'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update Image Tag in Kustomization
        run: |
          cd .k8s/overlays/prod
          kustomize edit set image sw-simple=evilpandas/sw-simple:${{ env.SHORT_TAG }} 

      - name: Deploy to Prod (Manual Approval)
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'argocd-deploy.yaml',
              ref: 'main',
              inputs: {
                environment: 'prod',
                image_tag: '${{ env.SHORT_TAG }}'
              }
            })